#!/bin/sh
# Agent: Writer
# Reads /context/findings.md, generates LaTeX paper, compiles PDF
set -e

# Install tools
apk add --no-cache -q curl jq texlive 2>/dev/null || apk add --no-cache -q curl jq 2>/dev/null

echo "=== Writer Agent Starting ==="

# Read findings from researcher
FINDINGS=""
if [ -f /context/findings.md ]; then
  FINDINGS=$(cat /context/findings.md)
  echo "Read findings: $(wc -c < /context/findings.md) bytes"
else
  echo "WARNING: No findings.md in context"
  FINDINGS="No research findings provided."
fi

TOPIC=$(grep "^**Topic:**" /context/brief.md | sed 's/\*\*Topic:\*\* //' || echo "Research")

# Call LLM to generate LaTeX
echo "Calling LLM for LaTeX generation..."

SYSTEM_PROMPT="You are a LaTeX expert. Generate a complete LaTeX research paper from the provided research findings. Include documentclass, packages, title, author (Agent-OS Pipeline), abstract, sections, and references. Output ONLY the LaTeX source code, nothing else. Use amsmath for equations. Escape special characters properly."

USER_PROMPT="Generate a LaTeX paper from these research findings:

Title: $TOPIC

Findings:
$(echo "$FINDINGS" | head -c 8000)"

RESPONSE=$(curl -s -X POST http://localhost:4000/api/v1/vm/llm/chat \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $JOB_TOKEN" \
  -d "$(jq -n \
    --arg sys "$SYSTEM_PROMPT" \
    --arg usr "$USER_PROMPT" \
    '{messages: [{role: "system", content: $sys}, {role: "user", content: $usr}], model: "gpt-4o", max_tokens: 8192}')" 2>&1)

if echo "$RESPONSE" | jq -e '.content' > /dev/null 2>&1; then
  echo "$RESPONSE" | jq -r '.content' > /shared/output/paper.tex
  echo "LaTeX generated: $(wc -c < /shared/output/paper.tex) bytes"
else
  echo "LLM proxy not available — generating minimal LaTeX"
  cat > /shared/output/paper.tex << 'LATEX'
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{hyperref}
\usepackage{amsmath}
\title{Research Paper}
\author{Agent-OS Pipeline}
\date{\today}
\begin{document}
\maketitle
\begin{abstract}
Research findings compiled by Agent-OS automated pipeline.
\end{abstract}
\section{Introduction}
This paper presents research findings.
\end{document}
LATEX
fi

# Compile PDF if pdflatex/tectonic available
if command -v pdflatex > /dev/null 2>&1; then
  echo "Compiling PDF with pdflatex..."
  cd /shared/output
  pdflatex -interaction=nonstopmode paper.tex > /dev/null 2>&1 || true
  if [ -f paper.pdf ]; then
    echo "PDF compiled: $(wc -c < paper.pdf) bytes"
  else
    echo "PDF compilation failed"
  fi
elif command -v tectonic > /dev/null 2>&1; then
  echo "Compiling PDF with tectonic..."
  cd /shared/output
  tectonic paper.tex > /dev/null 2>&1 || true
else
  echo "No LaTeX compiler available in VM — .tex file only"
fi

# Generate README
cat > /shared/output/README.md << README
# $TOPIC

## Agent Attribution

| Field | Value |
|-------|-------|
| **Pipeline** | Agent-OS Research Pipeline |
| **Researcher** | microVM agent (Alpine) |
| **Writer** | microVM agent (Alpine) |
| **Generated** | $(date -u +%Y-%m-%dT%H:%M:%SZ) |

## Summary

$(echo "$FINDINGS" | head -20)

---

*Generated by Agent-OS on $(date -u +%Y-%m-%dT%H:%M:%SZ)*
README

echo "=== Writer Agent Complete ==="
